# Generated by Django 5.0.6 on 2024-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_problem_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="correct_submissions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="problem",
            name="total_submissions",
            field=models.IntegerField(default=0),
        ),
    ]
