# Generated by Django 5.0.6 on 2024-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_problem_correct_submissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="correct_submissions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="problem",
            name="total_submissions",
            field=models.IntegerField(default=0),
        ),
    ]
