# Generated by Django 5.0.6 on 2024-07-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_problem_correct_submissions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="description",
            new_name="statement",
        ),
    ]
