# Generated by Django 5.0.6 on 2024-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_description_problem_statement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
