# Generated by Django 5.0.6 on 2024-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_testcase_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
